services:
  - type: web
    name: fitpilot-backend
    env: docker
    rootDir: backend
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: MONGODB_URL
        sync: false
      - key: MONGODB_DB_NAME
        value: fitpilot
